[build]
  base = "bug-tracking-system/frontend"
  publish = "dist"
  command = "npm ci && npx vite build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
